name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Docker Login
      env:
        DOCKER_USR: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USR -p $DOCKER_PASSWORD
        
    - name: Build Docker Image
      run: |
       docker build -t sem2410/docker-graphql:0.0.2 .
       docker build -t sem2410/docker-graphql:latest .
    - name: Push Docker Image
      run: | 
       docker push sem2410/docker-graphql:0.0.2
       docker push sem2410/docker-graphql:latest
         
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
